import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/security_report.dart';

class ExportService {
  static Future<void> exportToPdf(SecurityReport report) async {
    final pdf = pw.Document();
    final font = await PdfGoogleFonts.robotoCondensedRegular();
    final boldFont = await PdfGoogleFonts.robotoCondensedBold();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        theme: pw.ThemeData.withFont(base: font, bold: boldFont),
        build: (pw.Context context) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(30),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text("MOLTGUARD AI ANALYSIS", 
                          style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold, color: PdfColors.teal)),
                        pw.Text("Report ID: ${report.id}", 
                          style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
                      ],
                    ),
                    pw.BarcodeWidget(
                      barcode: pw.Barcode.qrCode(),
                      data: "https://moltguard.ai/verify/${report.id}",
                      width: 50, height: 50,
                    ),
                  ],
                ),
                pw.Divider(thickness: 1, color: PdfColors.teal),
                pw.SizedBox(height: 20),

                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    _buildStatCard("RISK SCORE",
                                   "${report.overallRiskScore.toInt()}%", _getRiskColor(report.overallRiskScore)),
                    _buildStatCard("THREAT LEVEL", report.riskLevel, _getRiskColor(report.overallRiskScore)),
                    _buildStatCard("VULNS FOUND", "${report.vulnerabilities.length}", PdfColors.blueGrey700),
                  ],
                ),
                pw.SizedBox(height: 30),

                _sectionTitle("EXECUTIVE SUMMARY"),
                pw.Text(report.summary, style: const pw.TextStyle(fontSize: 12)),

                pw.SizedBox(height: 20),
                _sectionTitle("VULNERABILITY DETAILS"),
                if (report.vulnerabilities.isEmpty)
                  pw.Container(
                    padding: const pw.EdgeInsets.all(10),
                    decoration: pw.BoxDecoration(color: PdfColors.green50, borderRadius: pw.BorderRadius.circular(5)),
                    child: pw.Text("PASSED: No malicious patterns detected.", 
                      style: const pw.TextStyle(color: PdfColors.green900, fontSize: 11)),
                  )
                else
                  ...report.vulnerabilities.map((v) => pw.Bullet(
                                        text: "${v.type} (${v.severity}): ${v.description}",
                    style: const pw.TextStyle(fontSize: 10),
                  )),

                pw.Spacer(),
                pw.Center(child: pw.Text("CONFIDENTIAL - Generated by Gemini 2.5 Flash", 
                  style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey))),
              ],
            ),
          );
        },
      ),
    );

    await Printing.layoutPdf(onLayout: (format) async => pdf.save(), name: "MoltGuard_${report.id}");
  }

  static pw.Widget _buildStatCard(String label, String value, PdfColor color) {
    return pw.Container(
      width: 140, padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: color, width: 1.5), 
        borderRadius: pw.BorderRadius.circular(8)
      ),
      child: pw.Column(
        children: [
          pw.Text(label, style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700)),
                    pw.Text(value, style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: color)),
        ],
      ),
    );
  }

  static pw.Widget _sectionTitle(String title) => pw.Padding(
    padding: const pw.EdgeInsets.only(bottom: 5),
    child: pw.Text(title, 
      style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: PdfColors.teal900)),
  );

  static PdfColor _getRiskColor(double score) {
    if (score >= 80) return PdfColors.red900;
    if (score >= 50) return PdfColors.orange900;
    return PdfColors.green900;
  }
}
